#!/usr/bin/env bash

set -eu -o pipefail

curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0

go get -u github.com/golang/dep/cmd/dep
